Create flow test resource example
kentik/terraform-provider-kentik-synthetics pull request #79
Opened 2022-02-08 12:50 UTC by jdziurzynski

KNTK-365

Created flow Test resource example and corrected other test examples to work correctly.

2022-02-09 10:48 UTC, danielfurman submitted a review, later dismissed

2022-02-15 06:22 UTC, mmac-m3a requested changes
The example `flow` test configuration is (mostly) OK. However, I've noticed couple problems in examples of other test types that I've unfortunately missed in previous reviews.

2022-02-15 06:22 UTC, mmac-m3a commented on docs/resources/test.md
>        protocol = "udp"
With `protocol = "udp"`, the `trace` config must define also `port`. I suggest to change the example and use `protocol = "icmp"`. Applies to all instances.

2022-02-15 06:22 UTC, mmac-m3a commented on docs/resources/test.md
>      ]
`dns` and `dns-grid` tests **must** have **only** `dns` in the `tasks` list. Those tests do not support running `ping` and `traceroute`.

2022-02-15 06:22 UTC, mmac-m3a commented on docs/resources/test.md
>      ]
`url` test must have `http` task in the task list.

2022-02-15 23:29 UTC, mmac-m3a approved these changes

2022-02-15 23:32 UTC, merged