Additional logs on debug level - improvements
kentik/terraform-provider-kentik-synthetics pull request #88
Opened 2022-02-24 15:06 UTC by jdziurzynski

KNTK - 262

Regarding to https://github.com/kentik/terraform-provider-kentik-synthetics/pull/86#issuecomment-1048658313
https://github.com/kentik/terraform-provider-kentik-cloudexport/pull/54#discussion_r812712734

2022-02-25 08:45 UTC, danielfurman requested changes

2022-02-25 08:45 UTC, danielfurman commented on synthetics/data_source_agent.go
> +	tflog.Debug(ctx, "Get synthetic Kentik API response", resp)
```suggestion
	tflog.Debug(ctx, "Get synthetic Kentik API response", "response", resp)
```
Could you show if the output of the log is correct? I think the Debug() API requires key-value pairs after the message.

In other places too.

2022-02-25 08:45 UTC, danielfurman commented on synthetics/data_source_agent.go
> +	tflog.Debug(ctx, "Get synthetic Kentik API request", "ID", d.Get(idKey).(string))
```suggestion
	tflog.Debug(ctx, "Get Agent Kentik API request", "ID", d.Get(idKey).(string))
```
The name of the resource is Agent.
In other places too.

2022-02-25 08:45 UTC, danielfurman commented on synthetics/data_source_tests.go
> +	tflog.Debug(ctx, "List synthetic Kentik API request")
```suggestion
	tflog.Debug(ctx, "List Tests Kentik API request")
```
The name of the resource is Test...
In other places too.

2022-03-02 11:33 UTC, danielfurman commented on synthetics/data_source_agent.go
> +	tflog.Debug(ctx, "Get synthetic Kentik API response", resp)
Done

2022-03-02 11:34 UTC, danielfurman commented on synthetics/data_source_agent.go
> +	tflog.Debug(ctx, "Get synthetic Kentik API request", "ID", d.Get(idKey).(string))
Done

2022-03-02 11:34 UTC, danielfurman commented on synthetics/data_source_tests.go
> +	tflog.Debug(ctx, "List synthetic Kentik API request")
Done

2022-03-02 11:34 UTC, danielfurman approved these changes

2022-03-08 06:28 UTC, mmac-m3a approved these changes

2022-03-08 06:29 UTC, merged